language: go

go:
    - "1.7.1"

git:
  submodules: false
 
before_install:
- openssl aes-256-cbc -K $encrypted_b62929797e29_key -iv $encrypted_b62929797e29_iv
  -in travis_key.enc -out travis_key -d
- sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
-git submodule update --init --recursive

before_script:
    - git clone --branch v2 https://github.com/go-yaml/yaml $GOPATH/src/gopkg.in/yaml.v2
    - go get -u -v github.com/spf13/hugo

script:
    - cd public
    - ./deploy.sh 

after_success:
    - echo "Hangar blog deployed"

