language: go

go:
    - "1.7.1"

    global:
        - SSH_KEY="travis_key_2"
        - GIT_NAME="Brtholomew Sullivan"
        - GIT_EMAIL="sullivan.bart@gmail.com"

before_install:
    - openssl aes-256-cbc -K $encrypted_b62929797e29_key -iv $encrypted_b62929797e29_iv -in travis_key_2.enc -out travis_key_2 -d

before_script:
    - git clone --branch v2 https://github.com/go-yaml/yaml $GOPATH/src/gopkg.in/yaml.v2
    - go get -u -v github.com/spf13/hugo

script:
    - ./deploy.sh

