language: go

go:
    - "1.7.1"

env:
    global:
        - SSH_KEY="id_rsa"
        - GIT_NAME="Roman Coedo"
        - GIT_EMAIL="romancoedo@gmail.com"
        - SOURCE_DIR="public"
        - DEPLOY_BRANCH="source"

before_install:
- openssl aes-256-cbc -K $encrypted_b62929797e29_key -iv $encrypted_b62929797e29_iv
  -in travis_key.enc -out ~\/.ssh/travis_key -d

before_script:
    - git clone --branch v2 https://github.com/go-yaml/yaml $GOPATH/src/gopkg.in/yaml.v2
    - go get -u -v github.com/spf13/hugo

script:
    - git clone https://github.com/rcoedo/hugo-steam-theme ./themes/hugo-steam-theme
    - hugo

after_success:
    - ./scripts/deploy.sh
