languageCode = "en-us"
BaseUrl= "https://farmradiohangar.github.io/"
LanguageCode= "en-us"
Title= "Farm Radio Hangar"
paginate = 5
DisqusShortname = "frihangar"
Copyright = "Copyleft - 2016"
canonifyurls = true

[params]
  description = "Farm Radio International's Hangar - Radio & ICT Innovation Lab"
  cover = "images/cover.jpg"
  author = "Hangar"
  authorlocation = "Arusha, Tanzania"
  authorwebsite = "http://www.farmradio.org"
  bio= "my bio"
  logo = "images/hangarlogo-trans.png"
  # googleAnalyticsUserID = "UA-79101-12"
  # Optional RSS-Link, if not provided it defaults to the standard index.xml
  # RSSLink = "http://feeds.feedburner.com/..."
  githubName = "FarmRadioHangar"
  twitterName = "FRIHangar"
  facebookName = "FriHangar"
  # linkedinName = ""
  # set true if you are not proud of using Hugo (true will hide the footer note "Proudly published with HUGO.....")
  hideHUGOSupport = false
  [params.social]
    twitter = "FRIHangar"

[[menu.main]]
  name = "Blog"
  weight = -120
  identifier = "blog"
  url = "/"

[[menu.main]]
  name = "Uliza"
  weight = -110
  identifier = "uliza"
  url = "/uliza"

[[menu.main]]
  name = "About us"
  weight = -110
  identifier = "about"
  url = "/about"
